idf_component_register(
    SRCS 
        "main.c"
        "drivers/pump_driver.c"
        "drivers/moisture_adc.c"
        "drivers/bme280_i2c.c"
        "system/sys_queues.h"
        "network/wifi_app.c"
        "network/mqtt_app.c"
    INCLUDE_DIRS 
        "."
        "drivers"
        "network"
        "system"
    REQUIRES 
        driver 
        esp_adc
        freertos
        log
        esp_driver_gpio
        esp_driver_i2c
        nvs_flash
        esp_wifi
        mqtt
)